Repository prgrms-web-devcourse-final-project/WEB1_1_Urdego_BE, pull requests merged in 2024-12, with the labels that each got.

#88 Main -> Develop
  docker-compose.yml
Labels: 🌏 Deploy

#91 Feature: 그룹 웹 소켓 기능 추가
  group_service/src/main/java/io/urdego/group_service/api/controller/group/api/GroupController.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/api/dto/request/CreateGroupReq.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/api/dto/request/UpdateGroupReq.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/api/dto/response/GroupCreateRes.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/api/dto/response/GroupInfoRes.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/api/dto/response/GroupListRes.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/api/dto/response/GroupRes.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/EventType.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/GroupMessageController.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/MessageDataReader.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/dto/EventType.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/dto/MessageRequest.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/dto/MessageResponse.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/request/MessageRequest.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/response/GameStartResponse.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/response/GroupMemberStatusResponse.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/response/GroupStatusResponse.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/response/MessageResponse.java
  group_service/src/main/java/io/urdego/group_service/api/controller/groupMember/GroupMemberController.java
  group_service/src/main/java/io/urdego/group_service/api/controller/groupMember/dto/request/AddGroupMemberReq.java
  group_service/src/main/java/io/urdego/group_service/api/service/group/GroupService.java
  group_service/src/main/java/io/urdego/group_service/api/service/group/GroupServiceImpl.java
  group_service/src/main/java/io/urdego/group_service/api/service/groupMember/GroupMemberService.java
  group_service/src/main/java/io/urdego/group_service/api/service/groupMember/GroupMemberServiceImpl.java
  group_service/src/main/java/io/urdego/group_service/common/client/UserServiceClient.java
  group_service/src/main/java/io/urdego/group_service/common/client/request/UserRequest.java
  group_service/src/main/java/io/urdego/group_service/common/client/response/UserInfo.java
  group_service/src/main/java/io/urdego/group_service/common/client/response/UserInfoResponse.java
  group_service/src/main/java/io/urdego/group_service/domain/entity/group/Group.java
  group_service/src/main/java/io/urdego/group_service/domain/entity/groupMember/GroupMember.java
  group_service/src/main/java/io/urdego/group_service/domain/entity/groupMember/repository/GroupMemberRepository.java
  user_service/src/main/java/io/urdego/user_service/api/controller/internal/InternalApiController.java
  user_service/src/main/java/io/urdego/user_service/api/controller/internal/request/UserRequest.java
  user_service/src/main/java/io/urdego/user_service/api/service/UserService.java
  user_service/src/main/java/io/urdego/user_service/api/service/UserServiceImpl.java
Labels: ✨ Feature

#101 BugFix: CORS 해결
  gateway_service/src/main/java/io/urdego/gateway_service/config/CorsConfiguration.java
Labels: 🐞 BugFix

#106 BugFix: CORS 해결
  content_service/src/main/java/io/urdego/content_service/common/config/ContentServiceConfig.java
  discovery_service/src/main/java/io/urdego/discovery_service/config/CorsConfig.java
  game_service/src/main/java/io/urdego/game_service/common/config/CorsConfig.java
  gateway_service/src/main/java/io/urdego/gateway_service/config/CorsConfiguration.java
  group_service/src/main/java/io/urdego/group_service/common/config/CorsConfig.java
  notification_service/src/main/java/com/example/notification_service/config/CorsConfig.java
  user_service/src/main/java/io/urdego/user_service/config/CorsConfiguration.java
Labels: 🐞 BugFix

#113 Feature(#93) : game-service 수정 및 WebSocket 추가
  game_service/build.gradle
  game_service/src/main/java/io/urdego/game_service/api/controller/game/GameController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/game/GameSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/game/dto/request/GameStartReq.java
  game_service/src/main/java/io/urdego/game_service/api/controller/player/PlayerController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/player/dto/response/PlayerRes.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/dto/request/RoundCreateReq.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/dto/response/RoundRes.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/dto/response/RoundStartRes.java
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/dto/request/SubmissionReq.java
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/dto/response/SubmissionRes.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameService.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/player/PlayerService.java
  game_service/src/main/java/io/urdego/game_service/api/service/player/PlayerServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/common/client/ContentServiceClient.java
  game_service/src/main/java/io/urdego/game_service/common/client/UserServiceClient.java
  game_service/src/main/java/io/urdego/game_service/common/client/dto/request/UserReq.java
  game_service/src/main/java/io/urdego/game_service/common/client/dto/response/UserInfoRes.java
  game_service/src/main/java/io/urdego/game_service/common/client/dto/response/UserRes.java
  game_service/src/main/java/io/urdego/game_service/common/config/WebSocketConfig.java
  game_service/src/main/java/io/urdego/game_service/common/exception/ExceptionMessage.java
  game_service/src/main/java/io/urdego/game_service/common/exception/player/PlayerException.java
  game_service/src/main/java/io/urdego/game_service/common/exception/user/UserException.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/game/Game.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/game/repository/GameRepository.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/player/Player.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/player/repository/PlayerRepository.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/round/repository/RoundRepository.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/submission/Submission.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/submission/repository/SubmissionRepository.java
Labels: ✨ Feature

#116 Feature(#93): game-service 배포
  game_service/build.gradle
  game_service/src/main/java/io/urdego/game_service/api/controller/game/GameController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/game/GameSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/game/dto/request/GameStartReq.java
  game_service/src/main/java/io/urdego/game_service/api/controller/player/PlayerController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/player/dto/response/PlayerRes.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/dto/request/RoundCreateReq.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/dto/response/RoundRes.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/dto/response/RoundStartRes.java
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/dto/request/SubmissionReq.java
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/dto/response/SubmissionRes.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameService.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/player/PlayerService.java
  game_service/src/main/java/io/urdego/game_service/api/service/player/PlayerServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/common/client/ContentServiceClient.java
  game_service/src/main/java/io/urdego/game_service/common/client/UserServiceClient.java
  game_service/src/main/java/io/urdego/game_service/common/client/dto/request/UserReq.java
  game_service/src/main/java/io/urdego/game_service/common/client/dto/response/UserInfoRes.java
  game_service/src/main/java/io/urdego/game_service/common/client/dto/response/UserRes.java
  game_service/src/main/java/io/urdego/game_service/common/config/WebSocketConfig.java
  game_service/src/main/java/io/urdego/game_service/common/exception/ExceptionMessage.java
  game_service/src/main/java/io/urdego/game_service/common/exception/player/PlayerException.java
  game_service/src/main/java/io/urdego/game_service/common/exception/user/UserException.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/game/Game.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/game/repository/GameRepository.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/player/Player.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/player/repository/PlayerRepository.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/round/repository/RoundRepository.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/submission/Submission.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/submission/repository/SubmissionRepository.java
Labels: ✨ Feature

#121 Feature(#93) : game 시작 및 round 종료 관련 로직 수정
  game_service/src/main/java/io/urdego/game_service/api/controller/game/GameController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/game/GameSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/game/dto/response/GameStartRes.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameService.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameServiceImpl.java
Labels: ✨ Feature

#122 Feature(#93): game 시작 및 round 종료 관련 로직 수정
  content_service/src/main/java/io/urdego/content_service/common/config/ContentServiceConfig.java
  game_service/src/main/java/io/urdego/game_service/api/controller/game/GameController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/game/GameSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/game/dto/response/GameStartRes.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameService.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameServiceImpl.java
Labels: ✨ Feature

#123 Refactor: 그룹 생성 API 수정
  group_service/src/main/java/io/urdego/group_service/api/controller/group/api/dto/request/CreateGroupReq.java
  group_service/src/main/java/io/urdego/group_service/api/service/group/GroupServiceImpl.java
  group_service/src/main/java/io/urdego/group_service/domain/entity/group/Group.java
Labels: 🔨 Refactor

#126 HotFix: 게임 쪽 주요 로직 개선, 웹소켓 테스트 완료
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/common/client/dto/response/GroupInfoRes.java
  game_service/src/test/java/io/urdego/game_service/DistanceAndScoreCalculatorTest.java
Labels: ✅ Test, 🐞 BugFix

#128 Feature(#127): 그룹 참여 로깅 추가
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/GroupMessageController.java
Labels: ✨ Feature

#131 Feature(#130): 그룹 참여 로깅 추가 2
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/GroupMessageController.java
Labels: ✨ Feature

#135 Refactor(#134): 웹 소켓 게임시작 메시지 응답 수정
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/GroupMessageController.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/response/GameStartResponse.java
Labels: 🔨 Refactor

#136 Feature: 그룹 생성 API - 게임 생성 요청 추가
  game_service/src/main/java/io/urdego/game_service/api/controller/game/GameController.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameService.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameServiceImpl.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/api/dto/request/GroupCreateReq.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/GroupMessageController.java
  group_service/src/main/java/io/urdego/group_service/api/service/group/GroupServiceImpl.java
  group_service/src/main/java/io/urdego/group_service/common/client/GameServiceClient.java
Labels: ✨ Feature

#139 Feature(#138) : add logback files
  .idea/compiler.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/content_service.main.iml
  .idea/modules/user_service.main.iml
  group_service/src/main/resources/logback-spring.xml
  user_service/src/main/resources/logback-spring.xml
Labels: ⚙ Setting

#140 Feature(#138): logback 설정
  .idea/compiler.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/content_service.main.iml
  .idea/modules/user_service.main.iml
  group_service/src/main/resources/logback-spring.xml
  user_service/src/main/resources/logback-spring.xml
Labels: ⚙ Setting

#141 HotFix(#138) : loki 관련 의존성 추가
  group_service/build.gradle
  group_service/src/main/resources/logback-spring.xml
  user_service/build.gradle
  user_service/src/main/resources/logback-spring.xml
Labels: 🐞 BugFix

#143 Hotfix(#138): modify gradle
  group_service/build.gradle
  user_service/build.gradle
Labels: 🐞 BugFix

#146 Refactor: userId -> nickname 변경
  content_service/src/main/java/io/urdego/content_service/api/user/controller/external/UserContentController.java
  content_service/src/main/java/io/urdego/content_service/common/client/UserServiceClient.java
  user_service/src/main/java/io/urdego/user_service/api/controller/internal/InternalApiController.java
Labels: 🔨 Refactor

#147 Refactor: 유저 전체 컨텐츠수 반환
  content_service/src/main/java/io/urdego/content_service/api/user/controller/external/response/UserContentListAndCursorIdxResponse.java
  content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentServiceImpl.java
  content_service/src/main/java/io/urdego/content_service/domain/entity/user/repository/UserContentRepositoryCustom.java
  content_service/src/main/java/io/urdego/content_service/domain/entity/user/repository/UserContentRepositoryImpl.java
Labels: ✨ Feature

#148 Refactor: userId -> nickname 변경
  content_service/src/main/java/io/urdego/content_service/api/user/controller/external/UserContentController.java
Labels: 🔨 Refactor

#149 Refactor: cursoridx 수정
  content_service/src/main/java/io/urdego/content_service/api/user/controller/external/response/UserContentListAndCursorIdxResponse.java
Labels: 🔨 Refactor

#150 Feature: round content limit 3으로 수정
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/modules.xml
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
Labels: ✨ Feature

#151 Refactor: Socket 구독 destination 전부 동적 경로로 처리
  game_service/src/main/java/io/urdego/game_service/api/controller/game/GameSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionSocketController.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/round/Round.java
Labels: ✨ Feature, 🔨 Refactor

#153 Feature(#152): Round 접근 요청 동시성 처리
  game_service/build.gradle
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/common/config/RedisConfig.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/round/repository/RoundRepository.java
Labels: ✨ Feature

#154 Feature(#152): 동시성 처리
  game_service/build.gradle
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/common/config/RedisConfig.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/round/repository/RoundRepository.java
Labels: ✨ Feature

#155 Refactor(#152) : 비관적 락 추가, 예외처리 문구 수정
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/round/repository/RoundRepository.java
Labels: ✨ Feature, 🔨 Refactor

#156 Refactor(#152): 라운드 생성 검증로직 비관적 락 추가
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/round/repository/RoundRepository.java
Labels: ✨ Feature, 🔨 Refactor

#157 Refactor(#152) : 로깅 개선, 점수 처리 로직 개선, 제출 관련 분산 락 수행
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#158 Refactor(#152): 로깅 개선, 점수 처리 로직 개선, 제출 관련 분산 락 수행
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
Labels: 🔨 Refactor

#159 Refactor(#152) : 점수처리 로직 개선, 라운드 정보 유저 브로드캐스팅 수정
  game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/round/repository/RoundRepository.java
Labels: ✨ Feature, 🔨 Refactor

#160 Refactor(#152) : 점수처리 로직 개선, 라운드 정보 유저 브로드캐스팅 수정
  game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/round/repository/RoundRepository.java
Labels: ✨ Feature, 🔨 Refactor

#165 Refactor(#152) : 레디스 TTL 수정
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
Labels: 🔨 Refactor

#166 Refactor(#152) : 레디스 TTL 수정
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
Labels: ✨ Feature
