Repository prgrms-web-devcourse-final-project/WEB1_1_Urdego_BE, pull requests merged in 2024-11, with the labels that each got.

#3 Docs(#1): Readme 수정
  README.md
Labels: 📃 Docs

#12 Feature(#4): 유저 컨텐츠 도메인 구현
  content_service/src/main/java/api/dto/user/UserContentController.java
  content_service/src/main/java/application/domain/user/UserContent.java
  content_service/src/main/java/application/port/in/UserContentService.java
  content_service/src/main/java/application/port/out/UserContentRepository.java
  content_service/src/main/java/application/service/user/UserContentServiceImpl.java
  content_service/src/main/java/common/exception/ContentException.java
  content_service/src/main/java/common/exception/ExceptionMessage.java
  content_service/src/main/java/common/exception/user/UserContentException.java
  content_service/src/main/java/infra/entity/BaseEntity.java
  content_service/src/main/java/infra/entity/user/UserContentEntity.java
  content_service/src/main/java/infra/entity/user/constant/ContentInfo.java
  content_service/src/main/java/infra/repository/user/UserContentJPARepository.java
  content_service/src/main/java/infra/repository/user/UserContentRepositoryImpl.java
  content_service/src/main/java/urdego/content_service/ContentServiceApplication.java
Labels: ✨ Feature

#20 Feature: User 1차 기능 개발
  .idea/misc.xml
  user_service/.gitignore
  user_service/build.gradle
  user_service/src/main/java/io/urdego/user_service/UserServiceApplication.java
  user_service/src/main/java/io/urdego/user_service/api/controller/ExceptionController.java
  user_service/src/main/java/io/urdego/user_service/api/controller/UserController.java
  user_service/src/main/java/io/urdego/user_service/api/controller/request/SignInRequest.java
  user_service/src/main/java/io/urdego/user_service/api/controller/request/SignUpRequest.java
  user_service/src/main/java/io/urdego/user_service/api/controller/request/VerifyNicknameRequest.java
  user_service/src/main/java/io/urdego/user_service/api/service/NicknameVerificationResult.java
  user_service/src/main/java/io/urdego/user_service/api/service/UserService.java
  user_service/src/main/java/io/urdego/user_service/api/service/UserServiceImpl.java
  user_service/src/main/java/io/urdego/user_service/api/service/exception/UserNotFoundException.java
  user_service/src/main/java/io/urdego/user_service/auth/config/SecurityConfig.java
  user_service/src/main/java/io/urdego/user_service/auth/jwt/JwtFilter.java
  user_service/src/main/java/io/urdego/user_service/auth/jwt/JwtProvider.java
  user_service/src/main/java/io/urdego/user_service/common/exception/CustomException.java
  user_service/src/main/java/io/urdego/user_service/common/exception/HttpStatusConstants.java
  user_service/src/main/java/io/urdego/user_service/config/CorsConfiguration.java
  user_service/src/main/java/io/urdego/user_service/config/SwaggerConfig.java
  user_service/src/main/java/io/urdego/user_service/domain/define/Role.java
  user_service/src/main/java/io/urdego/user_service/domain/define/User.java
  user_service/src/main/java/io/urdego/user_service/domain/define/UserRepository.java
  user_service/src/test/java/io/urdego/user_service/UserServiceImplApplicationTests.java
Labels: ✨ Feature

#22 Feature(#6): 그룹(게임 방) 관련 기능 개발
  .idea/vcs.xml
  group_service/.gitattributes
  group_service/.gitignore
  group_service/build.gradle
  group_service/gradle/wrapper/gradle-wrapper.jar
  group_service/gradle/wrapper/gradle-wrapper.properties
  group_service/gradlew
  group_service/gradlew.bat
  group_service/settings.gradle
  group_service/src/main/java/io/urdego/group_service/GroupServiceApplication.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/GroupController.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/request/CreateGroupReq.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/request/UpdateGroupReq.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/response/GroupListRes.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/response/GroupRes.java
  group_service/src/main/java/io/urdego/group_service/api/controller/groupMember/GroupMemberController.java
  group_service/src/main/java/io/urdego/group_service/api/controller/groupMember/dto/request/AddGroupMemberReq.java
  group_service/src/main/java/io/urdego/group_service/api/controller/groupMember/dto/response/GroupMemberListRes.java
  group_service/src/main/java/io/urdego/group_service/api/controller/groupMember/dto/response/GroupMemberRes.java
  group_service/src/main/java/io/urdego/group_service/api/service/group/GroupService.java
  group_service/src/main/java/io/urdego/group_service/api/service/group/GroupServiceImpl.java
  group_service/src/main/java/io/urdego/group_service/api/service/groupMember/GroupMemberService.java
  group_service/src/main/java/io/urdego/group_service/api/service/groupMember/GroupMemberServiceImpl.java
  group_service/src/main/java/io/urdego/group_service/common/exception/BaseException.java
  group_service/src/main/java/io/urdego/group_service/common/exception/ErrorResponse.java
  group_service/src/main/java/io/urdego/group_service/common/exception/ExceptionMessage.java
  group_service/src/main/java/io/urdego/group_service/common/exception/GlobalExceptionHandler.java
  group_service/src/main/java/io/urdego/group_service/common/exception/group/GroupException.java
  group_service/src/main/java/io/urdego/group_service/common/exception/groupMember/GroupMemberException.java
  group_service/src/main/java/io/urdego/group_service/domain/entity/BaseEntity.java
  group_service/src/main/java/io/urdego/group_service/domain/entity/group/Group.java
  group_service/src/main/java/io/urdego/group_service/domain/entity/group/repository/GroupRepository.java
  group_service/src/main/java/io/urdego/group_service/domain/entity/groupMember/GroupMember.java
  group_service/src/main/java/io/urdego/group_service/domain/entity/groupMember/GroupMemberRole.java
  group_service/src/main/java/io/urdego/group_service/domain/entity/groupMember/repository/GroupMemberRepository.java
  group_service/src/test/java/io/urdego/group_service/GroupServiceApplicationTests.java
Labels: ✨ Feature

#27 CI/CD(#26): 배포 플로우 구축, aws 환경 설정
  .github/workflows/deploy.yml
  discovery_service/Dockerfile
  docker-compose.yml
  gateway_service/Dockerfile
  group_service/Dockerfile
  user_service/Dockerfile
Labels: 🌏 Deploy, ⚙ Setting

#29 CI/CD(#26): merge Main to develop (ci/cd 테스트 때문에 main 브랜치에서 작업함)
  .github/workflows/deploy.yml
  discovery_service/Dockerfile
  gateway_service/Dockerfile
  group_service/Dockerfile
  group_service/build.gradle
  user_service/Dockerfile
  user_service/build.gradle
Labels: ✅ Test, 🐞 BugFix

#25 Feature(#24): 단일 컨텐츠 업로드
  content_service/build.gradle
  content_service/src/main/java/urdego/ContentServiceApplication.java
  content_service/src/main/java/urdego/api/user/controller/UserContentController.java
  content_service/src/main/java/urdego/api/user/controller/request/ContentUploadRequest.java
  content_service/src/main/java/urdego/api/user/service/UserContentService.java
  content_service/src/main/java/urdego/api/user/service/UserContentServiceImpl.java
  content_service/src/main/java/urdego/common/config/ContentServiceConfig.java
  content_service/src/main/java/urdego/common/config/multipart/MultipartConfig.java
  content_service/src/main/java/urdego/common/exception/ContentException.java
  content_service/src/main/java/urdego/common/exception/ErrorResponse.java
  content_service/src/main/java/urdego/common/exception/ExceptionMessage.java
  content_service/src/main/java/urdego/common/exception/GlobalExceptionHandler.java
  content_service/src/main/java/urdego/common/exception/aws/AwsException.java
  content_service/src/main/java/urdego/common/exception/user/UserContentException.java
  content_service/src/main/java/urdego/domain/entity/BaseEntity.java
  content_service/src/main/java/urdego/domain/entity/user/UserContent.java
  content_service/src/main/java/urdego/domain/entity/user/constant/ContentInfo.java
  content_service/src/main/java/urdego/domain/entity/user/repository/UserContentRepository.java
  content_service/src/main/java/urdego/external/aws/config/S3Config.java
  content_service/src/main/java/urdego/external/aws/service/S3Service.java
Labels: ✨ Feature

#42 Feature: 유저 서비스 - 닉네임으로 회원 목록 조회 추가
  user_service/build.gradle
  user_service/src/main/java/io/urdego/user_service/api/controller/external/UserController.java
  user_service/src/main/java/io/urdego/user_service/api/controller/external/request/SignInRequest.java
  user_service/src/main/java/io/urdego/user_service/api/controller/external/request/SignUpRequest.java
  user_service/src/main/java/io/urdego/user_service/api/controller/external/request/VerifyNicknameRequest.java
  user_service/src/main/java/io/urdego/user_service/api/controller/external/response/UserInfoResponse.java
  user_service/src/main/java/io/urdego/user_service/api/controller/internal/InternalApiController.java
  user_service/src/main/java/io/urdego/user_service/api/controller/internal/response/UserInfo.java
  user_service/src/main/java/io/urdego/user_service/api/controller/request/SignInRequest.java
  user_service/src/main/java/io/urdego/user_service/api/controller/request/VerifyNicknameRequest.java
  user_service/src/main/java/io/urdego/user_service/api/service/UserService.java
  user_service/src/main/java/io/urdego/user_service/api/service/UserServiceImpl.java
  user_service/src/main/java/io/urdego/user_service/common/constant/HttpStatusConstants.java
  user_service/src/main/java/io/urdego/user_service/common/exception/GlobalExceptionHandler.java
  user_service/src/main/java/io/urdego/user_service/common/exception/UserNotFoundException.java
  user_service/src/main/java/io/urdego/user_service/domain/UserRepository.java
  user_service/src/main/java/io/urdego/user_service/domain/entity/Role.java
  user_service/src/main/java/io/urdego/user_service/domain/entity/User.java
Labels: ✨ Feature

#46 Feature(#41): 다중 컨텐츠 업로드 + 컨텐츠 엔티티 수정
  content_service/build.gradle
  content_service/src/main/java/api/user/controller/UserContentController.java
  content_service/src/main/java/io/urdego/content_service/ContentServiceApplication.java
  content_service/src/main/java/io/urdego/content_service/api/user/controller/UserContentController.java
  content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentService.java
  content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentServiceImpl.java
  content_service/src/main/java/io/urdego/content_service/common/client/UserServiceClient.java
  content_service/src/main/java/io/urdego/content_service/common/client/response/UserResponse.java
  content_service/src/main/java/io/urdego/content_service/common/config/ContentServiceConfig.java
  content_service/src/main/java/io/urdego/content_service/common/config/multipart/MultipartConfig.java
  content_service/src/main/java/io/urdego/content_service/domain/entity/user/UserContent.java
  content_service/src/main/java/io/urdego/content_service/external/aws/service/S3Service.java
  user_service/src/main/java/io/urdego/user_service/api/controller/external/UserController.java
  user_service/src/main/java/io/urdego/user_service/api/controller/internal/InternalApiController.java
  user_service/src/main/java/io/urdego/user_service/api/controller/internal/response/UserResponse.java
  user_service/src/main/java/io/urdego/user_service/api/service/UserService.java
  user_service/src/main/java/io/urdego/user_service/api/service/UserServiceImpl.java
Labels: ✨ Feature

#53 Feature(#52): 컨텐츠 단일 삭제
  content_service/src/main/java/io/urdego/content_service/api/user/controller/UserContentController.java
  content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentService.java
  content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentServiceImpl.java
  content_service/src/main/java/io/urdego/content_service/common/config/ContentServiceConfig.java
  content_service/src/main/java/io/urdego/content_service/common/exception/ExceptionMessage.java
  content_service/src/main/java/io/urdego/content_service/common/exception/user/UserContentException.java
  content_service/src/main/java/io/urdego/content_service/external/aws/service/S3Service.java
Labels: ✨ Feature

#57 Feature(#55): 유저별 컨텐츠 조회
  content_service/.gitignore
  content_service/build.gradle
  content_service/src/main/java/io/urdego/content_service/api/user/controller/UserContentController.java
  content_service/src/main/java/io/urdego/content_service/api/user/controller/response/UserContentListAndCursorIdxResponse.java
  content_service/src/main/java/io/urdego/content_service/api/user/controller/response/UserContentResponse.java
  content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentService.java
  content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentServiceImpl.java
  content_service/src/main/java/io/urdego/content_service/domain/config/QueryDslConfig.java
  content_service/src/main/java/io/urdego/content_service/domain/entity/user/repository/UserContentRepository.java
  content_service/src/main/java/io/urdego/content_service/domain/entity/user/repository/UserContentRepositoryCustom.java
  content_service/src/main/java/io/urdego/content_service/domain/entity/user/repository/UserContentRepositoryImpl.java
Labels: ✨ Feature

#62 Feature(#51) : 알림 기능 구현
  .idea/misc.xml
  group_service/src/main/java/io/urdego/group_service/api/controller/group/GroupController.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/request/CreateGroupReq.java
  group_service/src/main/java/io/urdego/group_service/api/controller/groupMember/GroupMemberController.java
  notification-service/.idea/.gitignore
  notification-service/.idea/discord.xml
  notification-service/.idea/material_theme_project_new.xml
  notification-service/.idea/misc.xml
  notification-service/.idea/modules.xml
  notification-service/.idea/notification-service.iml
  notification-service/.idea/vcs.xml
  notification_service/.gitattributes
  notification_service/.gitignore
  notification_service/build.gradle
  notification_service/gradle/wrapper/gradle-wrapper.jar
  notification_service/gradle/wrapper/gradle-wrapper.properties
  notification_service/gradlew
  notification_service/gradlew.bat
  notification_service/settings.gradle
  notification_service/src/main/java/com/example/notification_service/NotificationServiceApplication.java
  notification_service/src/main/java/com/example/notification_service/api/controller/NotificationController.java
  notification_service/src/main/java/com/example/notification_service/api/controller/NotificationSseController.java
  notification_service/src/main/java/com/example/notification_service/api/controller/dto/NotificationRequestInfo.java
  notification_service/src/main/java/com/example/notification_service/api/service/NotificationPublisher.java
  notification_service/src/main/java/com/example/notification_service/config/RedisConfig.java
  notification_service/src/main/java/com/example/notification_service/config/RedisPubSubConfig.java
  notification_service/src/main/resources/application.yml
  notification_service/src/test/java/com/example/notification_service/NotificationServiceApplicationTests.java
Labels: ✨ Feature

#63 Feature(#58): 게임 컨텐츠 조회 구현
  content_service/src/main/java/io/urdego/content_service/api/user/controller/external/UserContentController.java
  content_service/src/main/java/io/urdego/content_service/api/user/controller/external/request/ContentUploadRequest.java
  content_service/src/main/java/io/urdego/content_service/api/user/controller/external/response/UserContentListAndCursorIdxResponse.java
  content_service/src/main/java/io/urdego/content_service/api/user/controller/external/response/UserContentResponse.java
  content_service/src/main/java/io/urdego/content_service/api/user/controller/internal/InternalApiController.java
  content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentService.java
  content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentServiceImpl.java
  content_service/src/main/java/io/urdego/content_service/common/client/UserServiceClient.java
  content_service/src/main/java/io/urdego/content_service/common/exception/ExceptionMessage.java
  content_service/src/main/java/io/urdego/content_service/domain/entity/user/repository/UserContentRepositoryCustom.java
  content_service/src/main/java/io/urdego/content_service/domain/entity/user/repository/UserContentRepositoryImpl.java
  user_service/src/main/java/io/urdego/user_service/api/controller/internal/InternalApiController.java
  user_service/src/main/java/io/urdego/user_service/api/service/UserService.java
  user_service/src/main/java/io/urdego/user_service/api/service/UserServiceImpl.java
  user_service/src/main/java/io/urdego/user_service/domain/UserRepository.java
Labels: ✨ Feature

#73 Feature(#72): 게임 단일 컨텐츠 정보 조회
  content_service/src/main/java/io/urdego/content_service/api/user/controller/external/response/UserContentResponse.java
  content_service/src/main/java/io/urdego/content_service/api/user/controller/internal/InternalApiController.java
  content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentService.java
  content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentServiceImpl.java
Labels: ✨ Feature

#74 Feature(#56): 게임 관련 rest api 구현
  game_service/build.gradle
  game_service/src/main/java/io/urdego/game_service/GameServiceApplication.java
  game_service/src/main/java/io/urdego/game_service/api/controller/game/GameController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/game/dto/request/GameStartReq.java
  game_service/src/main/java/io/urdego/game_service/api/controller/game/dto/response/GameRes.java
  game_service/src/main/java/io/urdego/game_service/api/controller/player/PlayerController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/player/dto/response/PlayerRes.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/dto/request/RoundCreateReq.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/dto/response/RoundRes.java
  game_service/src/main/java/io/urdego/game_service/api/controller/round/dto/response/RoundStartRes.java
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionController.java
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/dto/request/SubmissionReq.java
  game_service/src/main/java/io/urdego/game_service/api/controller/submission/dto/response/SubmissionRes.java
  game_service/src/main/java/io/urdego/game_service/api/dto/GroupServiceClient.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameService.java
  game_service/src/main/java/io/urdego/game_service/api/service/game/GameServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/player/PlayerService.java
  game_service/src/main/java/io/urdego/game_service/api/service/player/PlayerServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundService.java
  game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionService.java
  game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
  game_service/src/main/java/io/urdego/game_service/common/client/ContentServiceClient.java
  game_service/src/main/java/io/urdego/game_service/common/client/GroupServiceClient.java
  game_service/src/main/java/io/urdego/game_service/common/client/dto/response/ContentRes.java
  game_service/src/main/java/io/urdego/game_service/common/client/dto/response/GroupInfoRes.java
  game_service/src/main/java/io/urdego/game_service/common/config/CorsConfig.java
  game_service/src/main/java/io/urdego/game_service/common/config/SwaggerConfig.java
  game_service/src/main/java/io/urdego/game_service/common/exception/BaseException.java
  game_service/src/main/java/io/urdego/game_service/common/exception/ErrorResponse.java
  game_service/src/main/java/io/urdego/game_service/common/exception/ExceptionMessage.java
  game_service/src/main/java/io/urdego/game_service/common/exception/GlobalExceptionHandler.java
  game_service/src/main/java/io/urdego/game_service/common/exception/content/ContentException.java
  game_service/src/main/java/io/urdego/game_service/common/exception/game/GameException.java
  game_service/src/main/java/io/urdego/game_service/common/exception/player/PlayerException.java
  game_service/src/main/java/io/urdego/game_service/common/exception/round/RoundException.java
  game_service/src/main/java/io/urdego/game_service/common/exception/submission/SubmissionException.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/game/Game.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/game/repository/GameRepository.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/player/Player.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/player/repository/PlayerRepository.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/round/Round.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/round/repository/RoundRepository.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/submission/Submission.java
  game_service/src/main/java/io/urdego/game_service/domain/entity/submission/repository/SubmissionRepository.java
  gateway_service/.gitignore
  group_service/src/main/java/io/urdego/group_service/common/config/CorsConfig.java
Labels: ✨ Feature

#75 HotFix(#71): game-service 배포 워크플로 작성 및 https 연결을 위한 gateway 설정
  .github/workflows/deploy.yml
  .gitignore
  .idea/compiler.xml
  .idea/google-java-format.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/group_service.main.iml
Labels: 🌏 Deploy, 🥰 Accessibility, 🐞 BugFix

#77 HotFix(#71): game-service Dockerfile 추가
  game_service/Dockerfile
Labels: 🌏 Deploy

#78 game service Dockerfile 추가
  game_service/Dockerfile
Labels: 🌏 Deploy

#79 HotFix(#71): docker-compose gateway 443 수정
  docker-compose.yml
Labels: 🌏 Deploy

#80 HotFix(#71): docker-compose gateway volume 수정
  docker-compose.yml
Labels: 🌏 Deploy

#84 Feature : 그룹 생성 API 추가
  group_service/build.gradle
  group_service/src/main/java/io/urdego/group_service/api/controller/group/GroupController.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/request/CreateGroupReq.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/request/UpdateGroupReq.java
  group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/response/GroupCreateRes.java
  group_service/src/main/java/io/urdego/group_service/api/service/group/GroupService.java
  group_service/src/main/java/io/urdego/group_service/api/service/group/GroupServiceImpl.java
  group_service/src/main/java/io/urdego/group_service/api/service/groupMember/GroupMemberServiceImpl.java
  group_service/src/main/java/io/urdego/group_service/common/client/GameServiceClient.java
  group_service/src/main/java/io/urdego/group_service/common/client/NotificationServiceClient.java
  group_service/src/main/java/io/urdego/group_service/common/client/UserServiceClient.java
  group_service/src/main/java/io/urdego/group_service/common/client/request/GroupInfoReq.java
  group_service/src/main/java/io/urdego/group_service/common/client/request/NotificationRequestInfo.java
  group_service/src/main/java/io/urdego/group_service/common/client/request/UserNicknameRequest.java
  group_service/src/main/java/io/urdego/group_service/common/client/response/ResponseUserInfo.java
  group_service/src/main/java/io/urdego/group_service/common/client/response/UserIdListResponse.java
  group_service/src/main/java/io/urdego/group_service/domain/entity/group/Group.java
  user_service/src/main/java/io/urdego/user_service/api/controller/internal/InternalApiController.java
  user_service/src/main/java/io/urdego/user_service/api/controller/internal/response/UserIdListResponse.java
  user_service/src/main/java/io/urdego/user_service/api/controller/internal/response/UserNicknameRequest.java
  user_service/src/main/java/io/urdego/user_service/api/service/UserService.java
  user_service/src/main/java/io/urdego/user_service/api/service/UserServiceImpl.java
Labels: ✨ Feature
